name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install
      run: npm install
    - name: install dependencies
      run : npm i angular-cli-ghpages --save-dev
    - name: update gh-pages
      run: npm run update-gh-pages