name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: npm i angular-cli-ghpages --save-dev

    - name: build
      run: ng build --base-href "https://Jeido-RougeTerre.github.io/ExoAngular/"
    - name: deploy
      run: npx angular-cli-ghpages --dir=dist/exercice

permissions:
  contents: write 