name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install
      run: npm install
    - name: install angular
      run: npm install -g @angular/cli
    - name: install dependencies
      run : npm i angular-cli-ghpages --save-dev
    - name: build
      run: ng build --base-href "/ExoAngular/"
    - name: deploy
      run : npx angular-cli-ghpages --dir=dist/exercice/browser